### PR TITLE
cgmath->0.12.0; associated changes in teapot example

### PR DESCRIPTION
**Pull request by paulirotta**
Minor updates to teapot use of cgmath associated with version update 0.7->0.12 
Use of PI/2 constant in cgmath

### CODE REVIEW

**Comment by tomaka** [comment]
Thanks
r+, will merge when that travis thing with Cargo is fixed.

**Comment by tomaka** [comment]
Please remove the `.idea` thing. :-/

**Comment by paulirotta** [comment]
Sigh :)  Many of us use Intellij and it keeps that trash from the repo. Will do.

**Comment by tomaka** [comment]
Hopefully I don't forget to merge this time.

**Pull request merged**
