### PR TITLE
khr_physical_device_properties_2

### PR DESCRIPTION
**Pull request by nicokoch**
There are still some places left in vulkano, where the old functions get called unconditionally.
One example is the Image initialization where we never call `vkGetPhysicalDeviceFormatProperties2KHR`. These can be fixed later and are not included in this PR.

### CODE REVIEW

**Comment by tomaka** [comment]
I'm hesitating to merge because I don't like adding `#[derive]`s to items in vk-sys.

**Comment by nicokoch** [comment]
Yeah I don't like that part, too.
Any suggestions for a workaround?

**Comment by tomaka** [comment]
Instead of `vec![...; num]`, something like `(0 .. num).map(|_| ...).collect::<Vec<_>>()` should work as well.

**Comment by tomaka** [comment]
Closing in favor of #505

**Pull request closed without merging**
