### PR TITLE
rustfmt on all crates; rustfmt.toml with 400 char width

### LINKED ISSUE #266: Run rustfmt on the code
I just tried rustfmt again, and it looks like it produces much better code than before.
I guess it should be possible now to switch the coding style to this library.

This should be done once the `incoming` branch has been merged, otherwise it's going to be a very painful rebase.

### PR DESCRIPTION
**Pull request by paulirotta**
Fixes #266 

Making some lines less wide is an optional future change

### CODE REVIEW

**Comment by tomaka** [comment]
Thanks for the idea. Unfortunately I'd like to merge https://github.com/tomaka/vulkano/pull/321 (which is the branch I'm currently working on) into `incoming` first.

**Comment by paulirotta** [comment]
Something ugly happened with the CI anyway. I guess I trash this.

**Comment by tomaka** [comment]
The incoming branch doesn't pass CI. The tests haven't been updated for the new code yet.

**Comment by paulirotta** [comment]
Feel free to ping me when incoming is ready for such- I can take a fresh pass checking also tests.

**Pull request closed without merging**
