### PR TITLE
Update triangle example with swapchain recreation

### PR DESCRIPTION
**Pull request by mikedilger**
This is the start of a series of commits to add swapchain recreation to the examples (see #303).

Before I do the rest of them, I'd like feedback on this.

I'm also confused about something.  Without this code, when I resize the window, nothing bad happens.  Is that just the particular undefined behavior of my nvidia driver?  Or has something happened where recreating the swapchain manually is no longer necessary by users of vulkano?

### CODE REVIEW

**Comment by tomaka** [comment]
> I'm also confused about something. Without this code, when I resize the window, nothing bad happens. Is that just the particular undefined behavior of my nvidia driver? Or has something happened where recreating the swapchain manually is no longer necessary by users of vulkano?

Resizing a window usually does not trigger a out-of-date error for the swapchain (the specs don't say why such errors happen, but in practice it doesn't happen when resizing). Instead resizing a window will make the implementation return a "SUBOPTIMAL" success code which is not yet supported by vulkano.

Even if there was an error, there's no undefined behavior when drawing to an obsolete swapchain. It just doesn't work but it's allowed.

**Comment by tomaka** [comment]
As for your PR, unfortunately it doesn't work because the framebuffer object holds an `Arc` to the old swapchain image.
You need to reorganize the code to recreate the framebuffers as well.

This is probably something that the doc of swapchain should mention eventually as well.

**Comment by mikedilger** [comment]
> As for your PR, unfortunately it doesn't work because the framebuffer object holds an Arc to the old swapchain image.
> You need to reorganize the code to recreate the framebuffers as well.
 
Ok.  I notice in the example that the Command Buffers are created every loop iteration. Could it be rewritten so that the command buffers are only rebuilt when the swapchain/framebuffers are rebuilt?

**Comment by tomaka** [comment]
Technically there's nothing wrong in keeping command buffers alive when you can.

However I think it confuses beginners to do so.
In a real-world program it is very often impossible to keep command buffers alive between frames, and I think it's a good thing to show in the example that it's not a mistake to recreate them every time.

**Comment by mikedilger** [comment]
It seems a lot of things depend on the image dimensions:  depth buffer,  projection matrix (aspect ratio),  pipeline (viewport if Fixed).  Online tutorials also rebuild the render pass.  I find when I try to rebuild all this stuff, I wedge my graphics driver (nvidia under ubuntu).. and I'm worried about all the hard-power-offs I've had to do.  Maybe I should just back away from this and let someone with more experience in Vulkan take it on.

**Pull request closed without merging**
