### PR TITLE
Show error symbol instead of only raw int value.

### PR DESCRIPTION
**Pull request by Yamakaky**

### CODE REVIEW

**Comment by tomaka** [comment]
That's oddly specific for device creation. I don't want to introduce code in vulkano that helps people write an implementation.

**Comment by Yamakaky** [comment]
What do you mean? That's just a more precise error, without adding new lines of code.

**Comment by tomaka** [comment]
The code you modified only happens if the Vulkan implementation returns an error that it's not supposed to return. In other words it should basically never happen. `unreachable!()` would be appropriate as well for example.

There are tons of similar codes throughout vulkano, so I don't see why specifically device creation should show the enum value and not the other places.

**Comment by Yamakaky** [comment]
Ok

**Pull request closed without merging**
