### PR TITLE
Replace try! with more succinct '?'

### PR DESCRIPTION
**Pull request by paulirotta**
Reducing to modern standard syntax as per https://doc.rust-lang.org/std/macro.try.html

### CODE REVIEW

**Comment by tomaka** [comment]
Unfortunately this conflicts heavily with the `incoming` branch. I don't want to have to solve 250 conflicts when I try to merge it.

It's also a very superfluous change.

**Comment by paulirotta** [comment]
Let's wait for a better time to finish this. Do you generally prefer pull requests against 'incoming' or 'master'?

**Comment by tomaka** [comment]
"incoming" is preferred. Some parts of the code in "master" won't get any work anymore, because at this point several areas would have too many merge conflicts with "incoming".

Note that "incoming" temporary though. Once it's merged "master" will become the experimental branch again.

**Comment by tomaka** [comment]
I'm going to close this. I suppose there's no point in trying to fix all the conflits now.

**Pull request closed without merging**
