### PR TITLE
InstanceExtensions::supported()

### PR DESCRIPTION
**Pull request by Mixthos**
As suggested in #38.

I wanted it for [vulkano-info](https://github.com/Mixthos/vulkano-info), so I didn't wait for a reply. Sorry. ;)

`cargo test --lib` crashed without panicking, but that's likely because I had to switch to an NVIDIA GPU. :/

### CODE REVIEW

**Comment by tomaka** [comment]
I think the method name should reflect the fact that these are only the extensions supported by the core driver and not the .

**Comment by Mixthos** [comment]
> I think the method name should reflect the fact that these are only the extensions supported by the core driver and not the .

Did you mean "not by layers"? Maybe `supported_by_core()`?

**Comment by tomaka** [comment]
Yes for both.

**Comment by Mixthos** [comment]
I renamed it.

There should also be ways to query the extensions supported by layers and the layers and extensions supported by a physical device. Maybe this requires a rework of the layers and extensions modules?

**Pull request merged**
